glory_pay_homepage:
    path:   /pay/{id}
    defaults: { _controller: GloryPayBundle:Default:index }

glory_pay_process:
    path:   /pay/{service}/{id}
    defaults: { _controller: GloryPayBundle:Order:process }

glory_pay_notify:
    path:   /pay/{service}/notify
    defaults: { _controller: GloryPayBundle:Order:notify }
